### ISSUE TITLE
Full screen map with leaflet

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/userStories#1]
## Value Proposition

**As a User** 

**I want to see a map when i start the app.** 

**to be able to slide around in the map to get to different locations** 

## Description
<img width="303" alt="Bildschirmfoto 2022-12-09 um 13 15 07" src="https://user-images.githubusercontent.com/115305668/206710699-ca89c4d3-ad6a-49b6-9916-b94def1d5663.png">

Scribble / design or text

## Acceptance Criteria

- [ ] the map has to be on the full width and height of the viewfield
- [ ] You have to be able to zoom in and out on the map.
- [ ] You have to be able to maneuver on the map by swiping your finger over the app

## Tasks

(for developers team)

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] branch feature/mapConnect
- [ ] fetch and install the leaflet map api
- [ ] style the map to full width and height
- [ ] testing

**Comment by ufelgen** [comment]
Hallo Jan, das finde ich persönlich einen guten Einstieg in deine coole App! dein erster Punkt unter "Tasks" ist jetzt quasi, diese Tasks zu definieren - du bist ja gerade alleine das Dev Team, willst du die Tasks da vielleicht ausformulieren? (also hast du ja auch schon gemacht) vielleicht hab ich es auch falsch verstanden...
