### ISSUE TITLE
Pop-Up Infobox

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/userStories#3]
## Value Proposition

**As a User** 

**I want to see a Pop-Up Infobox when i click on a marker** 

**to get a short description about the Surfspot** 

## Description
<img width="282" alt="Bildschirmfoto 2022-12-09 um 14 01 07" src="https://user-images.githubusercontent.com/115305668/206719172-c2fd6533-562a-43c1-9865-a44a15d999c1.png">

## Acceptance Criteria

- [ ] there has to be a Pop-Up infobox when there is a click on a marker

## Tasks

(for developers team)

- [ ] branch feature/popUpInfobox
- [ ] creating a component called PopUpInfobox
- [ ] the component will be shown when the user clicks on the marker.
- [ ] the infobox includes a Header which is the name of the Surfspot, a paragraph which is the short Discription about the spot and an image which has an onclick function to close the infobox. 
- [ ] the title, and short description are probs, which will change when another marker is clicked
- [ ] testing
