### ISSUE TITLE
Component Surfspot Page

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/userStories#4]
## Value Proposition

**As a User** 

**I want to see a Page with information about the Surfspot when i click on a the pop-up box of the Surfspot** 

**to get more and detailed Information about the Surfspot** 

## Description
<img width="291" alt="Bildschirmfoto 2022-12-09 um 14 20 33" src="https://user-images.githubusercontent.com/115305668/206723181-5e663670-2cc1-41c0-9a1d-347b75bc51ac.png">

## Acceptance Criteria

- [ ] there has to be a detail page with more information about the Surfspot

## Tasks

(for developers team)

- [ ] branch feature/spotDetails
- [ ] creating a component called SpotDetails
- [ ] the component will be shown when the user clicks on the pop-up infobox.
- [ ] the SpotDetail page includes a picture of the spot, a h1 with the title of the spot, a h2 with the value Infos, a seperator, an paragraph with the short description, a seperator, a paragraph with the follow information: Surfbare Windrichtungen:
Besonderheiten: 
Surfschulen: 
Parkmöglichkeiten:, 
and a seperator
- [ ] the image, title, short description and the other informations are probs, which are coming from the Surfspots array
- [ ] testing
