### ISSUE TITLE
UseState for SurfSpots

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/userStories#5]
## Value Proposition

**As a User** 

**I want to get informations about a Surfspot** 

**to get this information they have to be stored somewhere** 

## Description

<img width="618" alt="Bildschirmfoto 2022-12-09 um 14 39 54" src="https://user-images.githubusercontent.com/115305668/206726491-9f0261a4-ba9b-4866-badc-ad923dc8b812.png">

## Acceptance Criteria

- [ ] there has to be a useState which includes an array with objects where information about a Surfspot are saved

## Tasks

(for developers team)

- [ ] branch feature/surfspotsArray
- [ ] creating a useState array which is called surfSpots
- [ ] there are objects in the array
- [ ] in each object are the following informations about a Surfspot: 
{Name: sdfsdf
Image: sdfsdf
Land: sdsdfsfd
Adresse: sdfsf
Koordinaten: sdfsdf
Beschreibung: sdfsd
Surfbare Winde: sdf
Besonderheiten: sdf
Surfschulen: sdfdsf
Parkmöglichkeiten: sdf
Übernachtungsmöglichkeiten: sdf}
- [ ] testing
