### ISSUE TITLE
List of Surfspots

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/userStories#6]
## Value Proposition

**As a User** 

**I want to see a list of all Surfspots** 

**to know which Surfboards are available in my app** 

## Description

<img width="302" alt="Bildschirmfoto 2022-12-12 um 08 28 48" src="https://user-images.githubusercontent.com/115305668/206998056-945fa192-b31d-47dc-9df9-67a23f5ef4f6.png">

## Acceptance Criteria

- [ ] there has to be a list of all Surfspots in my array
- [ ] In the list is for every Surfspot just the Name of the Spot visible

## Tasks

(for developers team)

- [ ] create branch feature/ListSurfspots
- [ ] create a component and a site for the list
- [ ] the list component returns a section 
- [ ] creating another component for the ListItems 
- [ ] the ListItems component returns a div within a h2(the value of the h2 is a prob) and a arrow which is a svg image 
- [ ] mapping over my Surfspot array and getting all the information of the spot as probs, for each Surfspot render a ListItem with the name of the spot as the h2 of the ListItem.
- [ ] The List item has a bottom border in blue (#699BF7)

**Comment by julialoeschel** [comment]
Hey
nice 👍 
An der Formulierung würde ich noch etwas schauben wollen: 

 - A list of all the Surfspot names (DELETE: that are in my array)
- An Array with Dummi data of the SurfSpots (gehört eher in Tasks)
- unter AC könntest du noch etwas über den Pfeil schreiben (der hat keine Funktion oder? dann sollte es auch erstmal kein Button sein --> brauchen wir den Pfeil hier dann schon?)
- die Tasks sind sehr Detailiert, hier könntest du so Details, welches HTML Element das ist und das du einen UseState brauchst gern rauslassen. 

sonst 👍
